const nodemailer = require('nodemailer');
const fs = require('fs');
var transport = nodemailer.createTransport({
    pool: true,
    host: 'smtp.gmail.com',
    port: 465,
    secure: true, // use SSL
    auth: {
      user: "sendinfo98@gmail.com", //example of generated by Mailtrap 
      pass: "vallvmuiihrnjohd" //example of generated by Mailtrap 
    }
  });
  let content = fs.readFileSync('../public/email/registration.html', "utf8");
  let data = {'name' : 'Jakarea Parvez', 'most' : 'MOST is replaced', 'survey' : ' SURZZVEY is repalces'}
  for (var key in data) {
    console.log("key " + key + " has value " + data[key]);
    content = content.replace("#"+key+"#", data[key])
  }
  //content = content.replace("#name#", "W3Schools").replace("#most#", "W3Schools").replace("#survey#", "W3Schools");
  console.log({content})
  var mailOptions = {
    from: 'sendinfo98@gmail.com',
    to: 'jakareaparvez@gmail.com',
    subject: 'Test Nodemailer with Mailtrap',
    html:  content,
    attachments: [
        {   // utf-8 string as an attachment
            filename: 'text.txt',
            content: 'Attachments'
        },
        {
            filename: 'logo',
            path: '../public/email/registration.html'
        }
      ]
  };
   
  transport.sendMail(mailOptions, (error, info) => {
    if (error) {
      return console.log(error);
    }
    console.log('Email sent: ' + info.response);
  });